export enum EventType {

    SIGNUP_EVENT = 'SIGNUP_EVENT',
  
    LOGIN_EVENT = 'LOGIN_EVENT',
  
    DEPOSIT_EVENT = 'DEPOSIT_EVENT',
  
    WITHDRAWAL_EVENT = 'WITHDRAWAL_EVENT',
  
    CREATE_SAVINGS_GOAL_EVENT = 'CREATE_SAVINGS_GOAL_EVENT',
  
    DELETED_SAVINGS_GOALS_EVENT = 'DELETED_SAVINGS_GOALS_EVENT',
  
    SAVINGS_ENDED_EVENT = 'SAVINGS_ENDED_EVENT',
  
    TRANSFER_TO_BEZO_EVENT = 'TRANSFER_TO_BEZO_EVENT',
  
    INTEREST_PAID_EVENT = 'INTEREST_PAID_EVENT',
  
    PASSWORD_RESET_INITIATED = 'PASSWORD_RESET_INITIATED',
  
    PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  
  }