export enum WITHDRAWL_DAILY_LIMIT_TYPE {
  DAILY_LIMIT_REACHED = 'DAILY_LIMIT_REACHED',
  DAILY_LIMIT_NOT_REACHED='DAILY_LIMIT_NOT_REACHED',
  WITHDRAWAL_LIMIT_REACHED = 'WITHDRAWAL_LIMIT_REACHED',
  WITHDRAWAL_LIMIT_NOT_REACHED='WITHDRAWAL_LIMIT_NOT_REACHED',
  USER_CAN_WITHDRAW='USER_CAN_WITHDRAW'

}

export enum WITHDRAWL_DAILY_LIMIT_STATUS {
  SUCCESS = 'SUCCESS',
  FAILED='FAILED',

}


