import { TransferService } from '../../transfers/services/transfer.service';
import { AccountDepositWithrawalDto } from './../../transfers/dto/AccountDepositDto';
import { AccountEntity } from './../../account/entities/account.entity';
import { InjectConnection } from '@nestjs/mongoose';
import { Connection } from 'mongoose';
import { Console, Command } from 'nestjs-console';
import { EntityManager } from 'typeorm';
import { SavingsGoalEntity } from '../../savings-goal/entities/savings-goal.entity';
import { TRANSACTION_TYPE } from '../../enums/transaction-type.enum';
import { MigrationDepositsEntity } from '../entitites/migration.deposits.entity';
import { MigrationService } from '../services/migration.service';
import { differenceInDays } from 'date-fns';
import { NotificationService } from '../../notifications/services/notification.service';
import { AuthUserEntity } from '../../auth/entities/auth-user.entity';
import { STATUS } from '../../auth/entities/enums/status.enum';
import { ReferralBoltEntity } from '../../referrals/entities/referral-bolt.entity';

@Console()
export class MigrateBoltDiscountCodesAccountsCommand {
  private db: Connection;
  constructor(
    private em: EntityManager,
    @InjectConnection() private connection: Connection,
    private service: MigrationService,
    private transferService: TransferService,
    private notificationService: NotificationService,
  ) {
    this.db = this.connection.useDb('bezosusuDBLive');
  }

  @Command({
    command: 'migrate:add-bolt-codes',
  })
  async execute(opts?: any) {
    try {
      return await this._execute(opts);
    } catch (e) {
      console.error(e);
      return 1;
    }
  }

  // write you
  async _execute(opts?: any) {
    console.log('Migrating interest ....');

    const boltRefCodes=['BEZO1PXK', 'BEZOQ2L6', 'BEZO524D', 'BEZOK9PY', 'BEZORMU7', 'BEZODQ1U', 'BEZO6HF8', 'BEZOFHRZ', 'BEZODL1F', 'BEZOEZZC', 'BEZOXTL2', 'BEZORPWH', 'BEZO5DMM', 'BEZO63FP', 'BEZOSESE', 'BEZORH92', 'BEZONV7V', 'BEZOHL7Q', 'BEZO5B3J', 'BEZO7MEY', 'BEZOJPA6', 'BEZO998S', 'BEZO5NCQ', 'BEZOF8KP', 'BEZOAWHQ', 'BEZO47BE', 'BEZOPYCR', 'BEZOKVEU', 'BEZOWX7N', 'BEZOJ9C1', 'BEZOWR3J', 'BEZO5LQJ', 'BEZO8N17', 'BEZOVXQ9', 'BEZOHU46', 'BEZO77TN', 'BEZOPA3W', 'BEZOMEFK', 'BEZO8VQQ', 'BEZO7TFE', 'BEZOK9Y8', 'BEZOUM4G', 'BEZOVXLJ', 'BEZON7FQ', 'BEZO2QT4', 'BEZOJ5AT', 'BEZOH8XD', 'BEZOP9PM', 'BEZO7S56', 'BEZOG1BC', 'BEZOM8RV', 'BEZOLYTE', 'BEZOYUZM', 'BEZOYPKM', 'BEZODDF8', 'BEZOVPSR', 'BEZO2SGR', 'BEZOXWV9', 'BEZO4KUE', 'BEZOG7ZW', 'BEZOFWLA', 'BEZOQPCF', 'BEZO2LSK', 'BEZOX66S', 'BEZO6N25', 'BEZO22K3', 'BEZOK3NT', 'BEZOL4LF', 'BEZO5JRC', 'BEZO7TMV', 'BEZOL514', 'BEZO4UGW', 'BEZOMFLS', 'BEZO1V85', 'BEZOX5M5', 'BEZOB3CB', 'BEZO4BRX', 'BEZOQRB8', 'BEZOS29H', 'BEZO8ZGD', 'BEZOYXJR', 'BEZOHNEZ', 'BEZOQPTM', 'BEZOMR6W', 'BEZOYM77', 'BEZOAXT6', 'BEZONX4C', 'BEZOQY1G', 'BEZOU3KD', 'BEZO94KY', 'BEZOHJDR', 'BEZOH785', 'BEZOS3UV', 'BEZOK5S5', 'BEZOSS72', 'BEZONZNW', 'BEZOGA87', 'BEZO9SLY', 'BEZOFFKS', 'BEZONE3R', 'BEZO2PGN', 'BEZOEPX6', 'BEZOXAD4', 'BEZOP23C', 'BEZOBNUG', 'BEZOJPSS', 'BEZOXME5', 'BEZO19AX', 'BEZOD7FK', 'BEZO9CG2', 'BEZOPZR6', 'BEZOM2YZ', 'BEZOS577', 'BEZOXRFR', 'BEZOEMV8', 'BEZOHHWF', 'BEZOBYKH', 'BEZOJ4X6', 'BEZOJEGC', 'BEZOTTZS', 'BEZO1VP7', 'BEZOK5DF', 'BEZO2S33', 'BEZOA8DE', 'BEZOM36P', 'BEZOTXKW', 'BEZOP6JP', 'BEZOLY6K', 'BEZOL88F', 'BEZOUK5Y', 'BEZOMX77', 'BEZORD29', 'BEZOPH3M', 'BEZORF1D', 'BEZO2L4Z', 'BEZOY985', 'BEZOBKBB', 'BEZO8PPN', 'BEZO2JD3', 'BEZOCBSG', 'BEZOEGR3', 'BEZO5G65', 'BEZOQBZN', 'BEZON5F4', 'BEZOHZR8', 'BEZO7U42', 'BEZOUQZE', 'BEZOR35G', 'BEZOT62G', 'BEZOJVCG', 'BEZO6E77', 'BEZOP1YP', 'BEZO4XRG', 'BEZOLTZL', 'BEZOVYYF', 'BEZO3B5G', 'BEZO22P1', 'BEZOGEWG', 'BEZOR5E9', 'BEZORRCM', 'BEZOBZS6', 'BEZO2AKN', 'BEZO3ZZR', 'BEZO56AB', 'BEZOPY8J', 'BEZOQ7DJ', 'BEZOKKMC', 'BEZO7CVH', 'BEZOSKQY', 'BEZOV3RB', 'BEZOXMR3', 'BEZO9ZWC', 'BEZOT7C4', 'BEZOTHP6', 'BEZOPS9Y', 'BEZOT7BE', 'BEZO112A', 'BEZOHGUV', 'BEZO211A', 'BEZON7R9', 'BEZO6EZ7', 'BEZOY58H', 'BEZO1EZ1', 'BEZOY75H', 'BEZOFK9A', 'BEZOHG38', 'BEZO77FZ', 'BEZOP26F', 'BEZO4WDL', 'BEZOG2KX', 'BEZOW5SV', 'BEZO4RC5', 'BEZOD2KB', 'BEZOB5WG', 'BEZOTE5N', 'BEZO43E5', 'BEZO2D25', 'BEZOYR8N', 'BEZOAT8T', 'BEZOP5PK', 'BEZOY1DG', 'BEZOMSLU', 'BEZOYJQC', 'BEZOXV83', 'BEZOBVAL', 'BEZOJL1U', 'BEZOGLKS', 'BEZOJ76G', 'BEZO736S', 'BEZOS1FQ', 'BEZO5CTQ', 'BEZOKVWE', 'BEZOAZU1', 'BEZO66GQ', 'BEZOPJ6F', 'BEZOBWEK', 'BEZOWWP9', 'BEZODY5T', 'BEZO1YVG', 'BEZOP2AK', 'BEZORKVN', 'BEZO3Y1D', 'BEZOW61P', 'BEZOTLJJ', 'BEZOUEB1', 'BEZOHR45', 'BEZOPWHC', 'BEZOARLC', 'BEZOECAA', 'BEZOM2CF', 'BEZOY3BK', 'BEZOWB2R', 'BEZOQUHB', 'BEZOV19Q', 'BEZO53KH', 'BEZO6DET', 'BEZOYR8U', 'BEZO8WTS', 'BEZOSUU6', 'BEZOXAL6', 'BEZOSRP9', 'BEZOLC7X', 'BEZO8UZN', 'BEZOUVNM', 'BEZOLUPA', 'BEZOGX6B', 'BEZO1M82', 'BEZOHJTY', 'BEZOW1YG', 'BEZOA1TG', 'BEZOB24Y', 'BEZOZZLD', 'BEZOYDA2', 'BEZOA4KN', 'BEZO7D77', 'BEZO21RC', 'BEZOZKR5', 'BEZO8NBJ', 'BEZOK2LK', 'BEZO7LUZ', 'BEZOWQY1', 'BEZOZ86R', 'BEZOY4EL', 'BEZOA4BE', 'BEZOVTX3', 'BEZOHSAZ', 'BEZOF36X', 'BEZOBGNN', 'BEZO8XWC', 'BEZOGFC1', 'BEZO3UNT', 'BEZOY4F9', 'BEZOVY8S', 'BEZOM7V1', 'BEZOPXW5', 'BEZOR66A', 'BEZOEFMR', 'BEZO92DE', 'BEZOUMV9', 'BEZOYZ9E', 'BEZOT67U', 'BEZOPP6F', 'BEZOAZFT', 'BEZOXRQZ', 'BEZOF38D', 'BEZOFH1P', 'BEZO698F', 'BEZOC819', 'BEZOERUR', 'BEZO1UUN', 'BEZOLCCT', 'BEZOSNXQ', 'BEZOKKV5', 'BEZO6FQA', 'BEZOQBHM', 'BEZO6Y2L', 'BEZOADZ8', 'BEZOESC8', 'BEZOBWJN', 'BEZO7S3U', 'BEZOXF7D', 'BEZOT9ZJ', 'BEZOP4RG', 'BEZOQHW1', 'BEZOVLS8', 'BEZON336', 'BEZOETB9', 'BEZOKQ5G', 'BEZO8QGG', 'BEZOEQWL', 'BEZOMFR3', 'BEZOJQWU', 'BEZOFSRW', 'BEZOZ24V', 'BEZOZJNV', 'BEZOBHUD', 'BEZORS3B', 'BEZOBZVU', 'BEZOQBFC', 'BEZOC8EP', 'BEZOF53E', 'BEZO1D8D', 'BEZO6E5L', 'BEZO3UJB', 'BEZOQRPW', 'BEZOUB24', 'BEZO9WVU', 'BEZORLNG', 'BEZO7LGK', 'BEZO9KLP', 'BEZOYVKA', 'BEZOC663', 'BEZO8D32', 'BEZOC84N', 'BEZOTSB2', 'BEZO4B95', 'BEZO8G85', 'BEZOVNML', 'BEZOZ279', 'BEZON1ED', 'BEZOJBEQ', 'BEZO2HR5', 'BEZOWM47', 'BEZOKMYJ', 'BEZOFKVP', 'BEZONVAH', 'BEZOM29F', 'BEZOGF77', 'BEZORS56', 'BEZO8GPG', 'BEZO5NSN', 'BEZOWEKE', 'BEZO68XV', 'BEZO5N56', 'BEZOU965', 'BEZOEDJE', 'BEZOZL4J', 'BEZOU122', 'BEZOPV1X', 'BEZOZETF', 'BEZO6XDD', 'BEZO6ZSG', 'BEZOW9ZE', 'BEZO9YRX', 'BEZOA57M', 'BEZORVDK', 'BEZODTBD', 'BEZOLUSP', 'BEZOS3A9', 'BEZODT9N', 'BEZO3ZD2', 'BEZOH4KW', 'BEZOLH7C', 'BEZOPG54', 'BEZOC5ZH', 'BEZO9VN2', 'BEZO4K93', 'BEZOGKB6', 'BEZOKLWW', 'BEZO5SZE', 'BEZO1BAQ', 'BEZO646C', 'BEZODS76', 'BEZOUB91', 'BEZOHE78', 'BEZO3Q44', 'BEZO6QE8', 'BEZOE7YD', 'BEZOD3WY', 'BEZOZ93D', 'BEZOGUFE', 'BEZOTJ54', 'BEZOPMFM', 'BEZO35RD', 'BEZOXUYZ', 'BEZON317', 'BEZOUWS4', 'BEZO9XLQ', 'BEZONRVY', 'BEZONCR1', 'BEZOMMJT', 'BEZO584N', 'BEZOFZHF', 'BEZOKZ8M', 'BEZOV2XR', 'BEZOLZZ3', 'BEZO8U4E', 'BEZO4XFX', 'BEZOMBW2', 'BEZOHJ67', 'BEZOHJ9M', 'BEZOQ288', 'BEZOQLF1', 'BEZOYW54', 'BEZOHG9R', 'BEZOUA3A', 'BEZOWDJ4', 'BEZOUJ8J', 'BEZOLYQ6', 'BEZOPN5L', 'BEZOA2XM', 'BEZOTD46', 'BEZODME6', 'BEZOD55U', 'BEZOK1GC', 'BEZOGB11', 'BEZO8SHL', 'BEZO6H3A', 'BEZOU3FZ', 'BEZOGSRX', 'BEZOYDXK', 'BEZO3ENQ', 'BEZOAJCE', 'BEZOANN9', 'BEZOFX8Z', 'BEZO1T9V', 'BEZOX94L', 'BEZO7PNK', 'BEZOE29F', 'BEZO5Z2G', 'BEZO32Z4', 'BEZOC5Y9', 'BEZOV9C2', 'BEZOALNR', 'BEZOCGDS', 'BEZOKN4U', 'BEZOHA8G', 'BEZOSBA7', 'BEZON1LU', 'BEZOH33Z', 'BEZOHN6D', 'BEZOKPKG', 'BEZOKHXJ', 'BEZOULV9', 'BEZO1KC4', 'BEZO7VEW', 'BEZO4F2B', 'BEZO6XSA', 'BEZO7YAL', 'BEZOD4QD', 'BEZOG14W', 'BEZO5N2G', 'BEZOLNPT', 'BEZOVUDH', 'BEZO5S6P', 'BEZOJZ38', 'BEZO7V1G', 'BEZOY83P', 'BEZOLZJ6', 'BEZO3ANQ', 'BEZO4PZD', 'BEZOFKM4', 'BEZOVKHC', 'BEZO4WJE', 'BEZO2PJN', 'BEZOC7GZ', 'BEZOXVPD', 'BEZOLFFH', 'BEZOZQET', 'BEZOJ4EP', 'BEZOJLDQ', 'BEZOR8JP', 'BEZOVVGN', 'BEZOLT7U', 'BEZO8QXF', 'BEZOPLDF', 'BEZO3WWY', 'BEZO8TCH', 'BEZOSKSK', 'BEZOXQE9', 'BEZONFCX', 'BEZOKQTR', 'BEZO7J8K', 'BEZO8BA3', 'BEZOPD9K', 'BEZOPP8K', 'BEZOH1SD', 'BEZOM9W5', 'BEZO43LJ', 'BEZOZW6X', 'BEZOD9Q9', 'BEZOHDHG', 'BEZOBFWL', 'BEZO6U3T', 'BEZO6CU5', 'BEZOSFGP', 'BEZOXJHY', 'BEZOVVA6', 'BEZO8ELF', 'BEZOETEL', 'BEZOW53S', 'BEZOXDUV', 'BEZOKXAZ', 'BEZOFV5M', 'BEZOEUU4', 'BEZOFWWC', 'BEZOMUEN', 'BEZOHFMW', 'BEZOTED7', 'BEZOMBBK', 'BEZODW23', 'BEZO2YST', 'BEZOGR87', 'BEZOPYEM', 'BEZO9Y5D', 'BEZO3W2Q', 'BEZOYGY7', 'BEZOA1CP', 'BEZOZVNB', 'BEZORCVK', 'BEZOVQNW', 'BEZOF11A', 'BEZOH9GP', 'BEZOKHEQ', 'BEZOCWWG', 'BEZO3MG5', 'BEZO25YN', 'BEZOBSFY', 'BEZOY8Y3', 'BEZOSU5X', 'BEZOQZTQ', 'BEZOQNUD', 'BEZO4RBM', 'BEZOBDTT', 'BEZOES2C', 'BEZOX9XX', 'BEZOEEUH', 'BEZO2ZTS', 'BEZOSR2H', 'BEZOT63M', 'BEZOQRTN', 'BEZOP6Y8', 'BEZOSK4M', 'BEZOK2GZ', 'BEZO3WCY', 'BEZOXA53', 'BEZO362V', 'BEZOE338', 'BEZOCH9Y', 'BEZOX635', 'BEZOYJEP', 'BEZOQYNC', 'BEZO9FCG', 'BEZO4G7B', 'BEZO3MK4', 'BEZOPWD8', 'BEZOVZMV', 'BEZON775', 'BEZO7U1F', 'BEZO8NCY', 'BEZOTCZV', 'BEZODEF5', 'BEZOVA5Z', 'BEZOXAED', 'BEZOJMGC', 'BEZOMFCF', 'BEZOUUYC', 'BEZO4LEB', 'BEZOGPSH', 'BEZOZK4T', 'BEZOTMKY', 'BEZO7DSB', 'BEZOR93X', 'BEZOTZEF', 'BEZOVAXZ', 'BEZOE32U', 'BEZOBVWH', 'BEZOEJGK', 'BEZOLX3X', 'BEZO59DV', 'BEZOHZCY', 'BEZOW1DR', 'BEZOD8B2', 'BEZOERFM', 'BEZOC96B', 'BEZOCKV8', 'BEZO6BCG', 'BEZOA7MP', 'BEZO5S8L', 'BEZO8TN6']


    const chunkSize = 20;
    for (let i = 0; i < boltRefCodes.length; i += chunkSize) {
       // console.log("result",result[i])
    
        const chunk = boltRefCodes.slice(i, i + chunkSize);
        console.log("chunk",chunk)

        const res = await Promise.all(
          chunk.map(async (dataInput) => {
            await this.saveBoltRefCodes(dataInput);
          }),
        );
      
    }
  }

  async saveBoltRefCodes(data: any) {
    //  const  getAssociatedAccount = await this.em.findOne(AccountEntity,{where:{id:data.accountId }})

    await this.em.save(ReferralBoltEntity,{
        code:data
    })
  }
}
